version: '3.7'

services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # the image will only initialize the database if the data directory is empty
      MYSQL_DATABASE: starterkit
      MYSQL_USER: starter
      MYSQL_PASSWORD: starter
      MYSQL_ROOT_PASSWORD: starter
    ports:
      - 3306:3306

  test-db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # the image will only initialize the database if the data directory is empty
      MYSQL_DATABASE: starterkit-test
      MYSQL_USER: starter
      MYSQL_PASSWORD: starter
      MYSQL_ROOT_PASSWORD: starter
    ports:
      - 6603:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports: 
      - 1025:1025
      - 8025:8025

  # is used for images resize on fly
  # https://docs.imgproxy.net/#/
  imgproxy:
    image: darthsim/imgproxy:latest
    environment: 
      - IMGPROXY_DOWNLOAD_BUFFER_SIZE=2097152
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENFORCE_WEBP=true
      - IMGPROXY_GZIP_BUFFER_SIZE=1048576
      - IMGPROXY_GZIP_COMPRESSION=5
      - IMGPROXY_KEY=646576656C6F706D656E74
      - IMGPROXY_SALT=646576656C6F706D656E74
    ports:
      - 5555:8080